/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef FLECS_BAKE_CONFIG_H
#define FLECS_BAKE_CONFIG_H

/* Headers of public dependencies */
/* No dependencies */

/* Convenience macro for exporting symbols */
/* Convenience macro for exporting symbols */
#undef flecs_STATIC
#if defined(flecs_EXPORTS)
  #if flecs_EXPORTS
    #if (defined(_MSC_VER) || defined(__MINGW32__))
      #define FLECS_API __declspec(dllexport)
    #else
      #define FLECS_API __attribute__((__visibility__("default")))
    #endif
  #else
    #if (defined(_MSC_VER) || defined(__MINGW32__))
      #define FLECS_API __declspec(dllimport)
    #else 
      #define FLECS_API
    #endif
  #endif
#else
  #define flecs_STATIC 1
  #define FLECS_API
#endif

#endif
